# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:48Xyph9bdSUsc7CxAzyygX1HuB0R1BlibRGk6Q42A9E=,iv:90/UE3lC86/pl8os2PgEd7kfZN4X2Bpf/5lnhQKJqm0=,tag:/j5ZL4lJ4iHeaoOwyYJuQA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h7q7jwlz3fyqkw7vme9k6hdvnaw5fnr0lk74t3t8g5j4sge6rvyqt5szhl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V1NEQ00wV05JcXBnR2d0
        OUVIK0ZpMFYrc0haTVcrMnhKYWhEYlJjKzBJCjZpZDAxQ3ozVnBtZzBlaUJLelNv
        V2NxWnZBR2h1VDB5MThsU05NQlBNUTgKLS0tIG42VTFoNTcrL2MwYnMwSHhod3pR
        RzVFTjdDRDd5ZmJBdXAwQkphNWIwdjQKh5jMGBwOtl7b5Rp7TY+q8VvEg03zGMWK
        4UffyUYIac+Tk+QkvZHKU2EuMZaMuN5nxQaMG8rp5S8R41J95hvzjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-06T18:03:00Z"
  mac: ENC[AES256_GCM,data:Qp1KDcDXmvXed08Ui+VRkaV6y/yQQs6m58Vkovsc571ZZasvqJoBUcSMKMn9kN5x+HA+mRIKb5XrKRCQb6HlPWppLLkxDR9HsTuThRkyvKc+2RU+bb8/FPVHpUe3U1pUpF3hSYqMa3FsMF2p6/gLO5FzgxqletevlSZro/kt1Xk=,iv:Y9O04/2/pJyolAyMR8DsUAsfat2syyhX6kw/Jl66EZU=,tag:ZUKaYy68W9L+TLvlB5D+kA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
